"use client";

// import Link from "next/link";
// import { Button } from "@/components/ui/button";
// import { motion } from "framer-motion";
// import { ArrowRight, CheckCircle2, Search, Zap, Heart, Briefcase } from "lucide-react";
// import { JobMarquee } from "@/components/landing/JobMarquee";

// export default function LandingPage() {
//   return (
//     <div className="flex flex-col min-h-screen">
//       {/* Hero Section */}
//       <section className="relative w-full py-20 lg:py-32 overflow-hidden bg-gradient-to-b from-background to-secondary/20">
//         <div className="absolute inset-0 bg-grid-black/[0.02] -z-10" />
//         <div className="container px-4 md:px-6 mx-auto">
//           <div className="flex flex-col items-center space-y-8 text-center">
//             <motion.div
//               initial={{ opacity: 0, y: 20 }}
//               animate={{ opacity: 1, y: 0 }}
//               transition={{ duration: 0.5 }}
//               className="space-y-4 max-w-3xl"
//             >
//               <div className="flex items-center justify-center gap-4 sm:gap-6 mb-6">
//                 <div className="w-14 h-14 sm:w-18 sm:h-18 md:w-20 md:h-20 rounded-2xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center shadow-xl shadow-indigo-500/30">
//                   <Briefcase className="w-7 h-7 sm:w-9 sm:h-9 md:w-10 md:h-10 text-white" />
//                 </div>
//                 <h1 className="text-5xl sm:text-6xl md:text-7xl lg:text-8xl font-black tracking-tighter">
//                   <span className="bg-clip-text text-transparent bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500">
//                     SwipeHire
//                   </span>
//                 </h1>
//               </div>
//               <p className="text-xl sm:text-2xl font-medium text-foreground/80 mb-2">
//                 Swipe Right on Your Dream Job
//               </p>
//               <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl">
//                 The content-first job discovery platform. Stop searching and start swiping.
//                 We use advanced AI to match your resume with the perfect opportunities.
//               </p>
//             </motion.div>

//             {/* Floating Marquee - Full Width */}
//             <motion.div
//               initial={{ opacity: 0 }}
//               animate={{ opacity: 1 }}
//               transition={{ delay: 0.3, duration: 0.8 }}
//               className="w-screen -mx-4 md:-mx-6 lg:-mx-[calc((100vw-1280px)/2+1.5rem)] -my-4"
//             >
//               <JobMarquee />
//             </motion.div>

//             <motion.div
//               initial={{ opacity: 0, y: 20 }}
//               animate={{ opacity: 1, y: 0 }}
//               transition={{ duration: 0.5, delay: 0.2 }}
//               className="flex flex-col sm:flex-row gap-4 mt-8"
//             >
//               <Link href="/login">
//                 <Button size="lg" className="h-12 px-8 text-lg gap-2 rounded-full shadow-lg shadow-primary/20 hover:shadow-primary/40 transition-all">
//                   Get Started
//                 </Button>
//               </Link>
//             </motion.div>

//           </div>
//         </div>
//       </section>

//       {/* Features Section */}
//       <section className="w-full py-20 bg-background">
//         <div className="container px-4 md:px-6 mx-auto">
//           <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
//             <FeatureCard
//               icon={<Search className="w-10 h-10 text-blue-500" />}
//               title="Smart Discovery"
//               description="Our AI analyzes your resume to surface jobs that actually match your skills and experience."
//               delay={0.1}
//             />
//             <FeatureCard
//               icon={<Heart className="w-10 h-10 text-pink-500" />}
//               title="Swipe to Apply"
//               description="Review job cards quickly. Swipe right to save or apply, swipe left to pass. Simple as that."
//               delay={0.2}
//             />
//             <FeatureCard
//               icon={<Zap className="w-10 h-10 text-yellow-500" />}
//               title="Instant Matches"
//               description="Get ranked recommendations instantly based on compatibility scores generated by our LLM."
//               delay={0.3}
//             />
//           </div>
//         </div>
//       </section>

//       {/* Footer */}
//       <footer className="w-full py-6 md:px-6 border-t bg-muted/40">
//         <div className="container mx-auto flex flex-col sm:flex-row justify-between items-center gap-4 text-center sm:text-left">
//           <p className="text-sm text-muted-foreground">
//             © 2024 SwipeHire. All rights reserved.
//           </p>
//           <div className="flex gap-4 text-sm text-muted-foreground">
//             <Link href="#" className="hover:underline hover:text-foreground">Privacy</Link>
//             <Link href="#" className="hover:underline hover:text-foreground">Terms</Link>
//           </div>
//         </div>
//       </footer>
//     </div>
//   );
// }

// function FeatureCard({ icon, title, description, delay }: { icon: React.ReactNode, title: string, description: string, delay: number }) {
//   return (
//     <motion.div
//       initial={{ opacity: 0, y: 20 }}
//       whileInView={{ opacity: 1, y: 0 }}
//       viewport={{ once: true }}
//       transition={{ duration: 0.5, delay }}
//       className="flex flex-col items-center text-center p-6 border rounded-2xl hover:shadow-lg hover:border-primary/50 transition-all bg-card"
//     >
//       <div className="mb-4 p-3 bg-secondary/50 rounded-xl">{icon}</div>
//       <h3 className="text-xl font-bold mb-2">{title}</h3>
//       <p className="text-muted-foreground">{description}</p>
//     </motion.div>
//   );
// }

import Header from '@/components/landing/Header';
import Hero from '@/components/landing/Hero';
import { JobMarquee } from '@/components/landing/JobMarquee';
import Features from '@/components/landing/Features';
import Velocity from '@/components/landing/Velocity';
import Footer from '@/components/landing/Footer';

const LandingPage = () => {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <Hero />
      <Features />
      <Footer />
    </div>
  );
};

export default LandingPage;
