import { Search, Heart, Zap } from 'lucide-react';
import { motion, useScroll, useTransform } from 'framer-motion';
import { useRef } from 'react';
import { JobMarquee } from '@/components/landing/JobMarquee';
import Velocity from '@/components/landing/Velocity';

const Features = () => {
  const containerRef = useRef<HTMLDivElement>(null);

  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ['start end', 'end center'],
  });

  // Container moves up as you scroll
  const y = useTransform(scrollYProgress, [0, 0.75], ['100vh', '0vh']);

  const features = [
    {
      icon: Search,
      title: 'Smart Discovery',
      description:
        'Our AI analyzes your resume to surface jobs that actually match your skills and experience.',
    },
    {
      icon: Heart,
      title: 'Swipe to Apply',
      description:
        'Review job cards quickly. Swipe right to save or apply, swipe left to pass.',
    },
    {
      icon: Zap,
      title: 'Instant Matches',
      description:
        'Get ranked recommendations instantly based on compatibility scores generated by our LLM.',
    },
  ];

  return (
    <motion.section
      id="features"
      ref={containerRef}
      style={{ y }}
      className="relative z-10 w-full  bg-background"
    >
      {/* Thin rectangular box wrapper */}
      <div className="border border-border/60 mx-6 md:mx-20 rounded-2xl overflow-hidden">
        {/* Features content */}
        <div className="max-w-[1400px] mx-auto px-6 md:px-20 py-20">
          <div className="grid lg:grid-cols-2 gap-24 items-center mb-32">
            {/* LEFT TEXT */}
            <div>
              <h2 className="text-4xl md:text-5xl font-bold mb-6">
                Why <span className="text-primary">SwipeHire?</span>
              </h2>
              <p className="text-muted-foreground max-w-md leading-relaxed">
                Built from the ground up to simplify your job search.
                Our AI-powered platform finds opportunities that actually match your skills.
              </p>
            </div>

            {/* RIGHT FEATURE CARDS */}
            <div className="relative flex flex-col items-end gap-6">
              {features.map((feature, index) => {
                const Icon = feature.icon;

                return (
                  <motion.div
                    key={feature.title}
                    initial={{ opacity: 0, y: 40 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    transition={{ delay: index * 0.15, duration: 0.6 }}
                    viewport={{ once: true }}
                    className="
                      w-[280px]
                      rounded-xl
                      bg-card/95
                      border border-border/60
                      shadow-xl shadow-black/30
                      p-6
                    "
                    style={{
                      marginRight:
                        index === 0 ? '0rem' : index === 1 ? '5rem' : '2rem',
                    }}
                  >
                    <Icon className="h-6 w-6 text-primary mb-4" />
                    <h3 className="text-base font-semibold mb-2">
                      {feature.title}
                    </h3>
                    <p className="text-sm text-muted-foreground leading-relaxed">
                      {feature.description}
                    </p>
                    <div className="mt-4 h-px bg-border/40" />
                  </motion.div>
                );
              })}
            </div>
          </div>
        </div>
      </div>

      {/* Job Marquee outside the box */}
      <div className="mt-8">
        <JobMarquee />
      </div>
      <div>
        <Velocity />
      </div>
    </motion.section>

  );
};

export default Features;